config/routes.rb
Rails.application.routes.draw do
  get 'recommendations/new'

  root 'welcome#index'

  resources :authors
  resources :articles do
    resources :recommendations, only: [:new, :create]
  end

  get 'weather'        => 'weather#show'
  get 'weather/update' => 'weather#update'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :author
  validates :title, presence: true, length: {
    minimum: 10,
    maximum: 100,
  }

  validates :content, presence: true, length: {
    minimum: 10,
    maximum: 1000,
  }

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :articles
end

app/models/recommendation.rb
class Recommendation

  include ActiveModel::Model

  attr_accessor :article, :email

  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  def send?

    ArticleMailer.recommend(article, email).deliver_later

  end

end

app/models/weather.rb
class Weather

  def self.read
    Rails.cache.read('weather')
  end

  def self.write
    require 'open-uri'
    json = open('http://api.openweathermap.org/data/2.5/weather?q=Sao_Paulo,br&units=metric').read
    hash = JSON.parse json
    hash['datetime'] = Time.now.to_i
    Rails.cache.write('weather', hash)
    hash
  end

  def self.fetch
    if read
      if age > 60
        WeatherUpdateJob.perform_later
      end
      read
    else
      write
    end
  end

  def self.age
    if read
      (Time.now - Time.at(read['datetime']).to_datetime) / 1.minute
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.

  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token, if: :json_request?
  layout proc { false if request.xhr? }

  protected

  def json_request?

    request.format.json?

  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to articles_url, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :author_id)
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :email)
    end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController

  before_action :set_article

  # GET /articles/1/recommendation/new

  def new

    @recommendation = Recommendation.new({ article: @article })

  end

  # POST /articles/1/recommendations

  # POST /articles/1/recommendations.json

  def create

    @recommendation = Recommendation.new({

        article: @article,

        email: recommendation_params[:email]

    })

    respond_to do |format|

      if @recommendation.valid? && verify_recaptcha(model: @recomendation) && @recommendation.send?

        format.html { redirect_to articles_url, notice: 'Recommendation was successfully created.' }

        format.json { render json: @recommendation }

      else

        format.html { render :new }

        format.json { render json: @recommendation.errors, status: :unprocessable_entity }

      end

    end

  end

  private

    # Use callbacks to share common setup or constraints between actions.

    def set_article

      @article = Article.find(params[:article_id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.

    def recommendation_params

      params.require(:recommendation).permit(:email)

    end

end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController

  def show

    render json: Weather.fetch

  end

  def update

    Weather.write

    redirect_to weather_url

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article, remote: request.xhr?) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.association :author %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= render 'layouts/flash' %>

<h1>Listing Articles</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Author</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td><%= article.author.name if article.author %></td>
        <td><%= link_to 'Recommend', new_article_recommendation_path(article) %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article Using Ajax', new_article_path, class: 'btn btn-primary', remote: true %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<p>
    <strong>Author:</strong>
    <%= @article.author.name if @article.author %>
</p>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/authors/_form.html.erb
<%= simple_form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<%= render 'layouts/flash' %>

<h1>Listing Authors</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.email %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path, class: 'btn btn-primary' %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>

  <%= content_tag :div, msg, class: "alert alert-#{name == 'notice' ? 'info' : name}" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsApz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div id="navbar">
      <ul class="nav navbar-nav">
        <%= link_to('Rails Apz', '/', class: 'navbar-brand') %>
        <li><%= link_to('Articles', articles_path) %></li>
        <li><%= link_to('Authors', authors_path) %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <p id="weather" class="navbar-text">Loading weather...</p>
      </ul>
    </div>
  </div>
</nav>

<div id="container" class="container">
  <%= yield %>
</div>

<div class="modal" id="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body"></div>
    </div>
  </div>
</div>

</body>
</html>

app/views/recommendations/_form.html.erb
<%= render 'layouts/flash' %>
<%= simple_form_for([@article, @recommendation]) do |f| %>
  <%= f.input :email %>
  <%= recaptcha_tags %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/recommendations/new.html.erb
<h1>New Recommendation</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/welcome/index.html.erb
<div class="jumbotron">

  <h1>Rails Apz</h1>

  <p>The guide to build a Rails app from a to z.</p>

  <p>

    <a class="btn btn-lg btn-primary" href="https://github.com/jp7internet/rails-apz" role="button">View On GitHub</a>

  </p>

</div>